name: Keep AI and Streamlit Alive

on:
  schedule:
    # Berjalan setiap 6 jam
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Hugging Face Space
      run: |
        curl -I -s https://achmadrifan-chatkasir.hf.space
        
    - name: Ping Streamlit Dashboard
      run: |
        curl -I -s https://dashboard-chatkasir.streamlit.app
